# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CT Data Visualization Guidelines
description: A resource on data visualization and accessibility for Connecticut state agencies
baseurl: "/data-visualization-guidelines" # the subpath of your site, e.g. /blog
url: "https://ctopendata.github.io/data-visualization-guidelines/" # the base hostname & protocol for your site, e.g. http://example.com

languages: ["en"]
default_lang: "en"

# Build settings
theme: just-the-docs
#remote_theme: pmarsceill/just-the-docs

aux_links: # remove if you don't want this link to appear on your pages
  Github Repository: https://github.com/ctopendata/data-visualization-guidelines/

favicon_ico: "/assets/favicon.ico"

search_enabled: true

# Footer
footer_navigation:
  previous:
    en: Previous
  next:
    en: Next

footer_hosted_with_love:
  en:
    label: "Hosted with love on GitHub"
    url: https://github.com/CTOpenData/data-visualization-guidelines

# Collections
collections:
  accessibility:
    output: true
    sort_by: nav_order
  data_visualization:
    output: true
    sort_by: nav_order
  equity:
    output: true
    sort_by: nav_order
  resources:
    output: true
    sort_by: nav_order

collections_dir: docs

defaults:
  - scope:
      path: "**/*.md"
      type: "accessibility"
    values:
      layout: "default"
  - scope:
      path: "**/*.md"
      type: "data_visualization"
    values:
      layout: "default"
  - scope:
      path: "**/*.md"
      type: "equity"
    values:
      layout: "default"
  - scope:
      path: "**/*.md"
      type: "resources"
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
